config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from virtual_library import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    # auth 
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    # profile
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/update/', views.ProfileUpdateView.as_view(), name='profile_update'),
    # product
    path('product-create/', views.ProductCreateView.as_view(), name='product_create'),
    path('product-detail/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    # order
    path('order-create/<int:id>/', views.OrderCreateView.as_view(), name='order_create'),
    path('order/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

virtual_library/models/book.py
from django.db import models

from .user import User
from .category import Category


class Book(models.Model):
    STATUS_CHOICES = (
        ('available', 'Available'),
        ('on_rent', 'On Rent'),
        ('sold', 'Sold'),
    )
    # book meta data
    title = models.CharField(max_length=100)
    cover_photo = models.ImageField(upload_to='media/book_covers', blank=True)
    author = models.CharField(max_length=100)
    published_date = models.DateField()
    description = models.TextField(blank=True)

    # product meta data
    owner = models.ForeignKey(User, related_name='books', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    price = models.IntegerField()
    rent = models.IntegerField()
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default=STATUS_CHOICES[0][0])
    available_from = models.DateField(null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.title} ({self.id})'

virtual_library/models/category.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return  f'{self.name} ({self.id})'

virtual_library/models/order.py
from django.db import models


class RentOrder(models.Model):
    user = models.ForeignKey('virtual_library.User', on_delete=models.CASCADE)
    book = models.ForeignKey('virtual_library.Book', on_delete=models.CASCADE)
    rent_date = models.DateField(auto_now_add=True)
    return_date = models.DateField(null=True, blank=True)
    is_returned = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user} - {self.book}'

    class Meta:
        verbose_name = 'Rent Order'
        verbose_name_plural = 'Rent Orders'


class ReturnOrder(models.Model):
    user = models.ForeignKey('virtual_library.User', on_delete=models.CASCADE)
    book = models.ForeignKey('virtual_library.Book', on_delete=models.CASCADE)
    return_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.book}'

    class Meta:
        verbose_name = 'Return Order'
        verbose_name_plural = 'Return Orders'

# on return order is_returned is set to True and book status is set to available

virtual_library/models/rating.py
from django.db import models

from .user import User
from .book import Book

class Rating(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(default=1)
    comment = models.TextField()
    
    class Meta: 
        unique_together = ('book', 'user')

virtual_library/models/user.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    phone = models.CharField(max_length=20, blank=True)
    address = models.CharField(max_length=100, blank=True)
    photo = models.ImageField(upload_to='media/user_photos', blank=True)
    

virtual_library/utils/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from virtual_library.models import User, Book

class RegisterForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2')


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        exclude = ['owner']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4, 'cols': 40}),
        }

virtual_library/views/authentication.py
from django.shortcuts import render, redirect
from django.contrib.auth import views as authviews
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model

from virtual_library.utils import RegisterForm


class LoginView(authviews.LoginView):
    template_name = 'login.html'
    redirect_authenticated_user = True

    def form_invalid(self, form):
        print(form.errors)
        return render(self.request, self.template_name, {'form': form})

class LogoutView(authviews.LogoutView):
    template_name = 'logout.html'


class RegisterView(generic.View):
    template_name = 'register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('login')
    
    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        return render(request, self.template_name, {'form': form})

virtual_library/views/home.py
from django.shortcuts import render
from django.views import generic
from django.db.models.aggregates import Avg


from virtual_library.models import Book

class HomeView(generic.View):
    template_name = 'home.html'

    def get(self, request, *args, **kwargs):
        query_string = request.GET.get('q')
        all_books = Book.objects.all().annotate(avg_rating=Avg('rating__rating'))
        filtered_books = self.filter_queryset(all_books, query_string)
        
        return render(request, self.template_name, {'books': filtered_books})

    def filter_queryset(self, queryset, query_string):
        if query_string:
            queryset = queryset.filter(title__icontains=query_string)
        return queryset
        

virtual_library/views/order.py
from datetime import datetime, timedelta

from django.views import generic
from django.shortcuts import redirect

from virtual_library.models import Book, RentOrder


class OrderDetailView(generic.DetailView):
    model = RentOrder
    template_name = 'order.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['order'] = self.object
        return context


class OrderCreateView(generic.View):

    def get(self, request, *args, **kwargs):
        order = self.create_new_order()
        self.update_order_info(order)
        return redirect('order_detail', pk=order.pk)

    def create_new_order(self):
        book = Book.objects.get(id=self.kwargs['id'])
        user = self.request.user
        return_date = self.get_return_date()
        order = RentOrder.objects.create(book=book, user=user, return_date=return_date)
        return order
    
    def update_order_info(self, order):
        order.book.status = 'on_rent'
        order.book.available_from = self.get_return_date()
        order.book.save()
        
    def get_return_date(self):
        return timedelta(days=30) + datetime.now().date()

virtual_library/views/product.py
from django.views import generic
from django.urls import reverse_lazy

from virtual_library.models import Book, Category

class ProductDetailView(generic.DetailView):
    model = Book
    template_name = 'product_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['book'] = self.object
        return context


class ProductCreateView(generic.CreateView):
    model = Book
    fields = ['title', 'author', 'description', 'price', 'rent', 'cover_photo', 'category', 'published_date']
    template_name = 'product_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['categories'] = Category.objects.all()
        return context

    def get_success_url(self):
        return reverse_lazy('product_detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

virtual_library/views/profile.py
from django.views import generic
from django.urls import reverse_lazy

from virtual_library.models import User

class ProfileView(generic.TemplateView):
    template_name = 'profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context


class ProfileUpdateView(generic.UpdateView):
    model = User
    fields = ['first_name', 'last_name', 'email', 'photo', 'phone', 'address']
    template_name = 'profile_update.html'

    def get_object(self):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy('profile')
        

virtual_library/templates/base.html
{% load static %}
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}Virtual Library</title>
    {% comment %} {% bootstrap_css %}
    {% bootstrap_javascript %} {% endcomment %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <!-- Font Awesome -->
<link
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
rel="stylesheet"
/>
<!-- Google Fonts -->
<link
href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
rel="stylesheet"
/>
<!-- MDB -->
<link
href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.4.0/mdb.min.css"
rel="stylesheet"
/>
    <style>
      #intro {
        /* Margin to fix overlapping fixed navbar */
        margin-top: 58px;
      }
      @media (max-width: 991px) {
        #intro {
          /* Margin to fix overlapping fixed navbar */
          margin-top: 45px;
        }
      }
    </style>
    {% block extra_head %}{% endblock extra_head %}
</head>
<body>
        

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
      <div class="container-fluid">
        <!-- Navbar brand -->
        <a class="navbar-brand" target="_blank" href="{% url 'home' %}">
          <img src="{% static 'assets/images/logo.png' %}" height="35" alt="" loading="lazy"
            style="margin-top: -3px;" />
          <span class="ms-1">470 Virtual Library</span>
        </a>
        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarExample01"
          aria-controls="navbarExample01" aria-expanded="false" aria-label="Toggle navigation">
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarExample01">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% comment %} <li class="nav-item active">
              <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
            </li> {% endcomment %}
            {% comment %} <li class="nav-item">
              <a class="nav-link" href="https://www.youtube.com/channel/UC5CF7mLQZhvx8O5GODZAhdA" rel="nofollow"
                target="_blank">Learn Bootstrap 5</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://mdbootstrap.com/docs/standard/" target="_blank">Download MDB UI KIT</a>
            </li> {% endcomment %}
          </ul>

          <ul class="navbar-nav d-flex flex-row">
            {% if request.user.is_authenticated %}
                <form action="{% url 'home' %}" class="d-flex col-12 col-lg-auto mb-3 mb-lg-0 me-5 me-lg-3" role="search">
                  <input name="q" type="text" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
                  <button type="submit" class="ms-3 btn btn-outline-warning">Search</button>
                </form>
                <div class="dropdown">
                  <a
                    class="dropdown-toggle d-flex align-items-center hidden-arrow"
                    href="#"
                    id="navbarDropdownMenuAvatar"
                    role="button"
                    data-mdb-toggle="dropdown"
                    aria-expanded="false"
                  >
                  {% if requset.user.photo %}
                  <img
                      src="{{ requset.user.photo.url }}"
                      class="rounded-circle""
                      height="35"
                      alt="Black and White Portrait of a Man"
                      loading="lazy"
                    />
                  {% else %}
                    <img
                      src="{% static 'assets/images/avatar-default.jpeg' %}"
                      class="rounded-circle""
                      height="35"
                      loading="lazy"
                    />
                  {% endif %}

                  </a>
                  <ul
                    class="dropdown-menu dropdown-menu-end"
                    aria-labelledby="navbarDropdownMenuAvatar"
                  >
                    <li>
                      <a class="dropdown-item" href="{% url 'product_create' %}">Add book</a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'profile' %}">My profile</a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'profile_update' %}">Edit Profile</a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    </li>
                  </ul>
                </div>
              </div>
            {% else %}
                    <div class="text-end">
                      <a href="{% url 'login' %}" class="btn btn-info me-2">Login</a>
                      <a href="{% url 'register' %}" class="btn btn-warning">Sign-up</a>
                    </div>
            {% endif %}
          </ul> 
        </div>
      </div>
    </nav>
    <!-- Navbar -->

    {% comment %} </header> {% endcomment %}
    
    {% block content %} {% endblock %}

    <!--Footer-->
  <footer class="bg-light text-lg-start">
    {% comment %} <div class="py-4 text-center">
      <a role="button" class="btn btn-primary btn-lg m-2"
        href="https://www.youtube.com/channel/UC5CF7mLQZhvx8O5GODZAhdA" rel="nofollow" target="_blank">
        Learn Bootstrap 5
      </a>
      <a role="button" class="btn btn-primary btn-lg m-2" href="https://mdbootstrap.com/docs/standard/" target="_blank">
        Download MDB UI KIT
      </a>
    </div> {% endcomment %}

    <hr class="m-0" />

    <div class="text-center py-4 align-items-center">
      <p>Follow us on social media</p>
      <a href="#" class="btn btn-primary m-1" role="button"
        rel="nofollow" target="_blank">
        <i class="fab fa-youtube"></i>
      </a>
      <a href="#" class="btn btn-primary m-1" role="button" rel="nofollow"
        target="_blank">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="#" class="btn btn-primary m-1" role="button" rel="nofollow"
        target="_blank">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="#" class="btn btn-primary m-1" role="button" rel="nofollow"
        target="_blank">
        <i class="fab fa-github"></i>
      </a>
    </div>

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2022 Copyright:
      <a class="text-dark" href="#!">470virtuallibrary.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!--Footer-->
  <!-- MDB -->
<script
type="text/javascript"
src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.4.0/mdb.min.js"
></script>
    {% block extra_footer %}
    {% endblock %}
</body>
</html>

virtual_library/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <!-- Jumbotron -->
  <div id="intro" class="p-5 text-center bg-light">
    <h1 class="mb-3 h2">Welcome to 470 Virtual Library</h1>
    <p class="mb-3">Never Stop Reading, Reading books is Now Easier and Cheaper!</p>
    <a class="btn btn-primary m-2" href="#!" role="button">Start exploring</a>
    <a class="btn btn-primary m-2" href="{% url 'product_create' %}" role="button">Share your book on Rent</a> 
  </div>
  <!-- Jumbotron -->

  <!--Main Navigation-->
  <!--Main layout-->
  <main class="my-5">
    <div class="container">
      <!--Section: Content-->
      <section>
        <div class="container py-5">
          <div class="row">
            {% for book in books %}
            <div class="col-md-12 col-lg-4 mb-4">
              <div class="card">
                <div class="d-flex justify-content-between p-3">
                  
                {% if book.cover_photo %}
                <img src="{{ book.cover_photo.url }}" class="card-img-top" style="width: 318px;" alt="Laptop" />
                {% else %}
                <img src="{% static 'assets/images/book-default.jpeg' %}" class="card-img-top" alt="Laptop" />
                {% endif %}
              </div>

                <div class="card-body">
                  <div class="d-flex justify-content-between">
                    <p class="small"><a href="#!" class="text-muted">
                      {% if book.category %}
                      {{ book.category.name }}
                      {% else %}
                      Uncategorized
                      {% endif %}
                      </a></p>
                  </div>
      
                  <div class="d-flex justify-content-between mb-3">
                    <a href="{% url 'product_detail' book.id %}"><h5 class="mb-0">{{book.title}}</h5></a>
                    <h5 class="text-dark mb-0">Tk.{{book.rent}}/mo</h5>
                  </div>
                  <div class="d-flex justify-content-between mb-2">
                    <p class="text-muted mb-0">Author: <span class="fw-bold">{{book.author}}</span></p>
                  </div>
                  <div class="d-flex justify-content-between mb-2">
                    <p class="text-muted mb-0">Available from: <span class="fw-bold">
                      {% if book.status == 'available' %}
                        Now
                      {% elif book.status == 'sold' %}
                      Not Available
                      {% else %}
                      {{book.availabe_from}}
                      {% endif %}

                    </span></p>
                    <div class="ms-auto text-warning">
                      {% if book.avg_rating %}
                      {{book.avg_rating|floatformat}}
                      {% else %}
                      N/A
                      {% endif %}
                      <i class="fa fa-star"></i>
                      {% comment %} 
                      <i class="far fa-star"></i>
                      <i class="fas fa-star-half-alt"></i>
                      {% endcomment %}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </section>
      <!--Section: Content-->

      <!-- Pagination -->
      <nav class="my-4" aria-label="...">
        <ul class="pagination pagination-circle justify-content-center">
          <li class="page-item">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
          </li>
          <li class="page-item"><a class="page-link" href="#">1</a></li>
          <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
          </li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item">
            <a class="page-link" href="#">Next</a>
          </li>
        </ul>
      </nav>
    </div>
  </main>
  <!--Main layout-->

  

{% endblock %}

virtual_library/templates/product_create.html
{% extends 'base.html' %}

{% block content %}
<div class="container m-5 p-5">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- 2 column grid layout with text inputs for the first and last names -->
        <div class="form-outline mb-4">
            <input name="title" type="text" id="form6Example1" class="form-control" />
            <label class="form-label" for="form6Example1">Title</label>
        </div>
        <div class="form-outline mb-4">
            <input name="author" type="text" id="form6Example1" class="form-control" />
            <label class="form-label" for="form6Example1">Author</label>
        </div>
        <!-- Text input -->
        <div class="form-outline mb-4">
          <input name="cover_photo" type="file" accept="image/png, image/gif, image/jpeg" id="form6Example3" class="form-control" />
          <label class="form-label" for="form6Example3"></label>
        </div>
      
        <!-- Text input -->
        <div class="form-outline mb-4">
          <input name="published_date" type="date" id="form6Example4" class="form-control" />
          <label class="form-label" for="form6Example4">Date Published</label>
        </div>
        
        <div class="form-outline mb-4">
            <textarea class="form-control" id="form6Example7" rows="3"></textarea>
            <label class="form-label" for="form6Example7">Description</label>
          </div>
    
        
      
        <div class="form-outline mb-4">
            <input name="price" type="number" id="form6Example6" class="form-control" />
            <label class="form-label" for="form6Example6">Price</label>
          </div>
    
        <div class="form-outline mb-4">
          <input name="rent" type="number" id="form6Example6" class="form-control" />
          <label class="form-label" for="form6Example6">Rent(monthly)</label>
        </div>
      
        <div class="form-outline mb-4">
            <select name="category" class="form-select" id="form6Example5" aria-label=" select example" >
                <option selected>Select Category</option>
                {% for category in categories %}
                <option value="{{category.id}}">{{category.name}}</option>
                {% endfor %}
            </select>
        </div>
    
       
      
      
        <!-- Submit button -->
        <button type="submit" class="btn btn-primary btn-block mb-4">Place book for Rent</button>
      </form>
</div>

{% endblock %}

virtual_library/templates/profile.html
{% extends 'base.html' %}

{% block content %}

<section style="background-color: #eee;">
    <div class="container py-5 my-5">
      <div class="row">
        <div class="col-lg-4">
                  <div class="card mb-4" style="border-radius: 15px;">
                    <div class="card-body text-center">
                      <div class="mt-3 mb-4">
                        {% if user.photo %}
                        <img src="{{ user.photo.url }}" alt="{{ user.username }}""
                          class="rounded-circle img-fluid" style="max-width: 100px;" />
                          {% else %}
                        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava2-bg.webp"
                          class="rounded-circle img-fluid" style="width: 100px;" />
                        {% endif %}

                      </div>
                      <h4 class="mb-2">{{user.first_name}} {{user.last_name}}</h4>
                      <p class="text-muted mb-4">@{{user.username}} 
                        {% comment %} <span class="mx-2">|</span> <a href="#!">mdbootstrap.com</a> {% endcomment %}
                      </p>
                      <div class="mb-4 pb-2">
                        <button type="button" class="btn btn-outline-primary btn-floating">
                          <i class="fab fa-facebook-f fa-lg"></i>
                        </button>
                        <button type="button" class="btn btn-outline-primary btn-floating">
                          <i class="fab fa-twitter fa-lg"></i>
                        </button>
                        <button type="button" class="btn btn-outline-primary btn-floating">
                          <i class="fab fa-skype fa-lg"></i>
                        </button>
                      </div>
                      {% comment %} <button type="button" class="btn btn-primary btn-rounded btn-lg">
                        Message now
                      </button> {% endcomment %}
                      <div class="d-flex justify-content-between text-center mt-5 mb-2">
                        <div>
                          <p class="mb-2 h5">{{user.balance}}</p>
                          <p class="text-muted mb-0">Wallets Balance</p>
                        </div>
                        <div class="px-3">
                          <p class="mb-2 h5">{{user.books.count|default:0}}</p>
                          <p class="text-muted mb-0">Total Books Listed</p>
                        </div>
                        <div>
                          <p class="mb-2 h5">{{user.rentorder_set.count|default:0}}</p>
                          <p class="text-muted mb-0">Total Books Rented </p>
                        </div>
                      </div>
                    </div>
                  </div>
          <div class="card mb-4 mb-lg-0">
            {% comment %} <div class="card-body p-0">
              <ul class="list-group list-group-flush rounded-3">
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fas fa-globe fa-lg text-warning"></i>
                  <p class="mb-0">https://mdbootstrap.com</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-github fa-lg" style="color: #333333;"></i>
                  <p class="mb-0">mdbootstrap</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-twitter fa-lg" style="color: #55acee;"></i>
                  <p class="mb-0">@mdbootstrap</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-instagram fa-lg" style="color: #ac2bac;"></i>
                  <p class="mb-0">mdbootstrap</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-facebook-f fa-lg" style="color: #3b5998;"></i>
                  <p class="mb-0">mdbootstrap</p>
                </li>
              </ul>
            </div> {% endcomment %}
          </div>
        </div>
        <div class="col-lg-8">
          <div class="card mb-4">
            <div class="card-body">
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Full Name</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{user.first_name}} {{user.last_name}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Email</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{user.email}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Mobile</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{user.phone}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Address</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{user.address}}</p>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="card mb-4 mb-md-0">
                <div class="card-body">
                  <h5 class="mb-4">Recently Listeds
                  </h5>
                  {% for book in user.books.all %}
                  <div class="card mb-2">
                    <div class="card-body">
                      <h5 class="card-title">{{book.title}}</h5>
                      <p class="card-text">Author: {{book.author}}</p>
                    </div>
                  </div>
                  {% empty %}
                  You have not listed any books.
                  {% endfor %}
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="card mb-4 mb-md-0">
                <div class="card-body">
                  <h5 class="mb-4">Recently Rented
                  </h5>
                  {% for order in user.rentorder_set.all %}
                  <div class="card">
                    <div class="card-body">
                      <h5 class="card-title">{{order.book.title}}</h5>
                      <p class="card-text">Author: {{order.book.author}}</p>
                    </div>
                  </div>
                  {% empty %}
                  You have not rented any books.
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}